project_name: fio-exporter

changelog:
  skip: false

release:
  prerelease: auto

builds:
  - id: fio-exporter
    main: exporter.go
    binary: fio-exporter
    ldflags:
    - -s
    - -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: fio-exporter
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - fio-exporter
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true

nfpms:
  - id: fio-exporter
    builds:
      - fio-exporter
    vendor: Aggelos Kolaitis
    homepage: https://github.com/neoaggelos/fio-exporter
    maintainer: Aggelos Kolaitis <neoaggelos@gmail.com>
    description: Prometheus exporter for FIO benchmarks
    license: Apache 2.0
    formats:
      - deb
      - rpm
    recommends:
      - fio

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    binaries:
      - fio-exporter
    image_templates:
      - "neoaggelos/fio-exporter:{{ .Version }}"
      - "neoaggelos/fio-exporter:latest"
    skip_push: auto
